/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/components/Astronaut.glb -o src/components/Astronaut.jsx 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three';

export function Astronaut(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/Astronaut.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, [actions, names]);

  /*
  actions: 이 객체는 glTF 모델에서 추출한 애니메이션 액션들의 맵이다. 각 애니메이션 액션은 이름에 따라 키,값 쌍으로 매핑된다. 각 액션은 애니메이션을 조작하는데 사용된다.
  names: 이 배열은 glTF 모델에서 추출된 모든 애니메이션의 이름 목록이다.
  */

  return (
    <group ref={group} {...props} dispose={null} position={[0.7, -1.13, 0]}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Astronaut" geometry={nodes.Astronaut.geometry} material={materials.Astronaut} skeleton={nodes.Astronaut.skeleton}/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/Astronaut.glb')