/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Room.glb -o src/components/Room.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('models/Room.glb')
  return (
    <group {...props} dispose={null} position={[0,-1.5,0]}>
      <group position={[0.004, 0.002, -1.331]}>
        <mesh geometry={nodes.Cube073.geometry} material={materials.Wall_01} />
        <mesh geometry={nodes.Cube073_1.geometry} material={materials.Wall_02} />
        <mesh geometry={nodes.Cube073_2.geometry} material={materials.Wall_04} />
      </group>
      <group position={[-1.418, 0.002, 0.003]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials.Wall_01} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials.Wall_02} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials.Wall_03} />
        <mesh geometry={nodes.Cube020_3.geometry} material={materials.Wall_04} />
      </group>
      <group position={[0.782, 0.413, -0.324]}>
        <mesh geometry={nodes.Cube066.geometry} material={materials.Bed1_2} />
        <mesh geometry={nodes.Cube066_1.geometry} material={materials.Bed1_1} />
        <mesh geometry={nodes.Cube066_2.geometry} material={materials.Bed1_3} />
      </group>
      <group position={[0.032, 0.118, -1.067]}>
        <mesh geometry={nodes.Cube067.geometry} material={materials.Bed1_2} />
        <mesh geometry={nodes.Cube067_1.geometry} material={materials.BedTable1_1} />
      </group>
      <group position={[-0.737, 2.011, -1.231]}>
        <mesh geometry={nodes.Cylinder061.geometry} material={materials.Clock1_1} />
        <mesh geometry={nodes.Cylinder061_1.geometry} material={materials.Clock1_2} />
      </group>
      <mesh geometry={nodes.Bowl.geometry} material={materials.Bowl1_1} position={[-1.198, 0.811, -1.068]} />
      <group position={[-0.753, 0.823, -0.872]}>
        <mesh geometry={nodes.Cube068.geometry} material={materials.KeyBoard1_2} />
        <mesh geometry={nodes.Cube068_1.geometry} material={materials.KeyBoard1_1} />
      </group>
      <group position={[-0.41, 0.847, -0.867]}>
        <mesh geometry={nodes.Cube069.geometry} material={materials.Mouse1_2} />
        <mesh geometry={nodes.Cube069_1.geometry} material={materials.Mouse1_1} />
      </group>
      <group position={[-0.366, 0.308, -0.999]}>
        <mesh geometry={nodes.Cube077.geometry} material={materials.PC1_1} />
        <mesh geometry={nodes.Cube077_1.geometry} material={materials['PC1-2']} />
      </group>
      <group position={[-0.748, 0.879, -1.093]}>
        <mesh geometry={nodes.Cube078.geometry} material={materials.PCs1_1} />
        <mesh geometry={nodes.Cube078_1.geometry} material={materials.PCs1_2} />
        <mesh geometry={nodes.Cube078_2.geometry} material={materials.PCs1_3} />
      </group>
      <mesh geometry={nodes.PC_mouse.geometry} material={materials.PCMouse1_1} position={[-0.421, 0.82, -0.868]} />
      <mesh geometry={nodes.Table.geometry} material={materials.TableRoom2_1} position={[-0.726, 0.796, -0.918]} />
      <group position={[-0.182, 0.819, -1.124]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.plant_01} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.plant_04} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.plant_05} />
      </group>
      <group position={[-1.121, 0.121, 1.269]}>
        <mesh geometry={nodes.Cylinder023.geometry} material={materials.plant_01} />
        <mesh geometry={nodes.Cylinder023_1.geometry} material={materials.plant_02} />
        <mesh geometry={nodes.Cylinder023_2.geometry} material={materials.plant_03} />
      </group>
      <group position={[0.035, 0.496, -1.063]}>
        <mesh geometry={nodes.Cube297.geometry} material={materials.Book_02} />
        <mesh geometry={nodes.Cube297_1.geometry} material={materials.Book_01} />
      </group>
      <group position={[-1.322, 1.808, 0.996]}>
        <mesh geometry={nodes.Cylinder045.geometry} material={materials.Darts_01} />
        <mesh geometry={nodes.Cylinder045_1.geometry} material={materials.Darts_02} />
        <mesh geometry={nodes.Cylinder045_2.geometry} material={materials.Darts_03} />
        <mesh geometry={nodes.Cylinder045_3.geometry} material={materials.Darts_04} />
      </group>
      <group position={[-1.212, 0.828, -0.836]}>
        <mesh geometry={nodes.Cube141.geometry} material={materials.Book_01} />
        <mesh geometry={nodes.Cube141_1.geometry} material={materials.Book_02} />
        <mesh geometry={nodes.Cube141_2.geometry} material={materials.Book_03} />
      </group>
      <group position={[-1.335, 0.201, -0.496]}>
        <mesh geometry={nodes.Cube145.geometry} material={materials.socket_01} />
        <mesh geometry={nodes.Cube145_1.geometry} material={materials.socket_02} />
      </group>
      <mesh geometry={nodes.SwitchLight.geometry} material={materials.socket_01} position={[-1.321, 0.984, 1.31]} />
      <group position={[-0.281, 0.809, -1.111]}>
        <mesh geometry={nodes.Cube160.geometry} material={materials.lamp_01} />
        <mesh geometry={nodes.Cube160_1.geometry} material={materials.Lamp_02} />
        <mesh geometry={nodes.Cube160_2.geometry} material={materials.Lamp_03} />
      </group>
      <group position={[-1.254, 1.742, 0.006]}>
        <mesh geometry={nodes.Cylinder057.geometry} material={materials.Curtains_01} />
        <mesh geometry={nodes.Cylinder057_1.geometry} material={materials.Curtains_02} />
      </group>
      <group position={[0.004, 0.012, 0.006]}>
        <mesh geometry={nodes.Cube095.geometry} material={materials.Floor5_1} />
        <mesh geometry={nodes.Cube095_1.geometry} material={materials.Floor5_2} />
        <mesh geometry={nodes.Cube095_2.geometry} material={materials.Floor5_3} />
        <mesh geometry={nodes.Cube095_3.geometry} material={materials['Floor5_1.001']} />
        <mesh geometry={nodes.Cube095_4.geometry} material={materials['Floor5_2.001']} />
        <mesh geometry={nodes.Cube095_5.geometry} material={materials['Floor5_3.001']} />
      </group>
      <group position={[-0.816, 0.12, -0.41]}>
        <mesh geometry={nodes.Cube061.geometry} material={materials.Chair_01} />
        <mesh geometry={nodes.Cube061_1.geometry} material={materials.Chair_03} />
        <mesh geometry={nodes.Cube061_2.geometry} material={materials.Chair_04} />
        <mesh geometry={nodes.Cube061_3.geometry} material={materials.Chair_05} />
      </group>
      <group position={[0.836, 1.56, -1.224]}>
        <mesh geometry={nodes.Cube619.geometry} material={materials.Picture_01} />
        <mesh geometry={nodes.Cube619_1.geometry} material={materials.Picture_04} />
      </group>
      <group position={[0.985, 2.003, -1.224]}>
        <mesh geometry={nodes.Cube623.geometry} material={materials.Picture_01} />
        <mesh geometry={nodes.Cube623_1.geometry} material={materials.Picture_02} />
      </group>
      <group position={[0.611, 1.949, -1.224]}>
        <mesh geometry={nodes.Cube624.geometry} material={materials.Picture_01} />
        <mesh geometry={nodes.Cube624_1.geometry} material={materials.Picture_03} />
      </group>
      <mesh geometry={nodes.Flower_03.geometry} material={materials.plant_01} position={[-1.121, 0.121, 1.269]} />
      <mesh geometry={nodes.Bed_01.geometry} material={materials.Bed1_1} position={[0.788, 0.559, -0.84]} />
    </group>
  )
}

useGLTF.preload('models/Room.glb');